### ISSUE TITLE
[next] Collect user data next to refresh tokens (discussion)

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#133]
ex

- current_ip
- device_data
- geo location

Maybe `device_data` from the request should match the `device_data` in the database in order for the `refresh_token` to be valid.

Open to hearing what other have to say.

**Comment by Aervue** [comment]
I agree, and I would rename the refresh_tokens table to sessions as they're basically that :)

https://webkay.robinlinus.com/ is a good example of stuff we can put in device_data

I don't think it's a good idea to directly compare current device data to the old device_data (might be wrong):
- Upgrade/downgrade browser versions will probably output a different user agent.
- Some browsers like chrome allow me to do a master login (or sync?) using my google account. If I move from windows to macOS for example, it will change the OS version in device_data but keep my cookies.

Another suggestion would be to compare IP's (similar to what Google does).
- User is logged in with IP X
- User comes back later and has IP Y (because he has a dynamic IP from ISP)
- Once X is different from Y, check if X & Y are from same country, if yes, allow, if not, invalidate the session. (I remember there was some node package with a database to do this).

If I have 10 tabs open, and one refresh token cookie is updated in a tab, will the rest of the 9 tabs be updated in real-time? (I have another suggestion if yes)

Also, regarding the JWT refresh, I would suggest the following:
- If JWT expiry is set at 15 minutes, do a silent refresh at exactly that.
- If JWT silent refresh fails (because of stuff like putting PC to sleep before and waking it up after) then make the request at the next API request (or altogether ditch the silent refresh in favor of this).
- Every time a JWT refreshes, increase the refresh_token expiration time so that it's always 30 days (or whatever value we choose) available since the last refresh.

**Comment by plmercereau** [comment]
What would happen it the same user opens two sessions in the same time?

**Comment by elitan** [comment]
> What would happen if the same user opens two sessions in the same time?

If you mean two sessions on two different devices I don't think it's a problem. They will be on two different refresh_tokens.

**Comment by plmercereau** [comment]
Should this be solved prior to the v2 release?

**Comment by elitan** [comment]
No, let's leave it for post v2.0.0

**Comment by MarcelloTheArcane** [comment]
Will this need to consider GDPR and other restrictions on collecting personally identifiable information?

**Comment by elitan** [comment]
I don't think so given what I just read here:

https://law.stackexchange.com/questions/28603/how-to-satisfy-gdprs-consent-requirement-for-ip-logging

**Comment by elitan** [comment]
We could use something like https://github.com/yusukeshibata/express-fingerprint

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
