### ISSUE TITLE
[next] Return JWT earlier in the registration process

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#148]
- When auto activation of users is activated, the `/auth/register` endpoint could return the JWT
- When users need to be activated, the `/auth/account/activate` endpoint could return the JWT

To illustrate the idea: https://github.com/accounts-js/accounts/releases/tag/v0.25.0

**Comment by elitan** [comment]
Instead of returning the JWT, we could simply set the refresh token cookie and redirect the user to the frontend app. The frontend app should automatically be able to log in the user based on the refresh token cookie we have set.

So:

We should have an env var specifying the URL to the frontend app. Ex `FRONTEND_APP_URL` or `APP_URL`

If `FRONTEND_APP_URL` is set. We should:
- Set refresh token cookie
- Redirect to `FRONTEND_APP_URL`

on the following routes:

- `/auth/register`
- `/auth/account/activate`
- `auth/change-password/change`

-----------

To consider, how will this work on mobile apps?

**Comment by elitan** [comment]
"Yup makes sense to set the refresh token cookie. Not such a big deal for the register endpoint. As you can just call login straight after register returns."

**Comment by MichaelJCole** [comment]
@elitan the only think I'd add to your proposal is a {{JWT_TOKEN}} replacement in the URL to support the non-cookie JWT path.

**Comment by elitan** [comment]
Implemented.
