### ISSUE TITLE
Error: field "user_accounts" not found in type: 'users_insert_input' even after tracking tables 

### ISSUE THREAD

**Issue by lslima91** [nhost/hasura-backend-plus#208]
I'm getting the same error as described here: https://github.com/nhost/hasura-backend-plus/issues/93

I'm tracking all tables from the auth schema.
https://i.imgur.com/aoZGmZf.png

**Comment by SkinyMonkey** [comment]
Did you add the right permissions for the user table in hasura?
Data > users (table) > permissions > user role, add rights to read

**Comment by ppseafield** [comment]
For the record - I ran into this as well. The solution in #93 was incomplete for me, but it did put me on the correct path.

I got this error when sending a post to `/auth/local/register`:

```
shell $ docker logs 9185d504df57
2020-05-05T05:25:45: PM2 log: Launching in no daemon mode
2020-05-05T05:25:45: PM2 log: [Watch] Start watching backend-hasura-plus
2020-05-05T05:25:45: PM2 log: App [backend-hasura-plus:0] starting in -fork mode-
2020-05-05T05:25:45: PM2 log: App [backend-hasura-plus:0] online
auth active
auth local active
storage active
listening on port 3010
{ Error: field "user_accounts" not found in type: 'users_insert_input': {"response":{"errors":[{"extensions":{"path":"$.variableValues.user.user_accounts","code":"validation-failed"},"message":"field \"user_accounts\" not found in type: 'users_insert_input'"}],"status":200},"request":{"query":"\n  mutation (\n    $user: users_insert_input!\n  ) {\n    insert_users (\n      objects: [$user]\n    ) {\n      affected_rows\n    }\n  }\n  ","variables":{"user":{"display_name":"wtfmate","active":true,"secret_token":"dfcb3bb2-47ac-458d-aa48-0f496d818e66","user_accounts":{"data":{"username":"wtfmate","password":"$2a$10$6cT/N6NP1jI5wnvecRPgbuL2fPzIwPO8h4C9O/9Z59VPswdPyfF66"}}}}}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/src/index.js:116:35)
    at step (/app/node_modules/graphql-request/dist/src/index.js:40:23)
    at Object.next (/app/node_modules/graphql-request/dist/src/index.js:21:53)
    at fulfilled (/app/node_modules/graphql-request/dist/src/index.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  response: { errors: [ [Object] ], status: 200 },
  request:
   { query:
      '\n  mutation (\n    $user: users_insert_input!\n  ) {\n    insert_users (\n      objects: [$user]\n    ) {\n      affected_rows\n    }\n  }\n  ',
     variables: { user: [Object] } } }
Unable to create user.
Error: Unable to create user.
    at router.post (/app/src/auth/local.js:72:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I had to switch the schema to `auth` and track there.

![image](https://user-images.githubusercontent.com/734908/81037809-d630a580-8e58-11ea-919b-e0da2ee44340.png)

Click "Track All"

![image](https://user-images.githubusercontent.com/734908/81037868-09733480-8e59-11ea-8db9-4b652a6987c2.png)

Then go BACK to the public schema and track the new relations.

![image](https://user-images.githubusercontent.com/734908/81037974-64a52700-8e59-11ea-8dc8-68efdff9a002.png)

This isn't mentioned in the README, which just says 

```Go to the Hasura console. Click the "Data" menu link and then click "Track all" under both "Untracked tables or views" and "Untracked foreign-key relations"```

I wonder if this happened because of some change to `db-init.sql`. Originally when I ran that, it failed because I couldn't track `set_current_timestamp_updated_at`.

**Comment by plmercereau** [comment]
My guess is that parts of the schema is not being tracked by Hasura, either in the `public` schema or in the `auth` schema.
@ppseafield I think your problem with `set_current_timestamp_updated_at` was due to the fact that the `db-init.sql` is trying to create the function while it already exists i.e. Hasura have created it already when you created your own tables. We will correct this In the version 2 of Hasura Backend Plus. By the way, in v2 the migrations will most likely load automatically so you don't need to load the SQL script manually from the console.
Another trick that could solve the problem is to reload the metadata, either, from the console or from the CLI with `hasura metadata reload`.
I hope it helps

**Comment by ryoid** [comment]
Was getting the same error, @ppseafield solution works.

After tacking all tables I had to go back to the schema and track relations as well.

**Comment by ppseafield** [comment]
@plmercereau This was the error I got regarding `set_current_timestamp_updated_at`:

```{
    "internal": [
        {
            "definition": {
                "schema": "public",
                "name": "set_current_timestamp_updated_at"
            },
            "reason": "in function \"set_current_timestamp_updated_at\": the function \"set_current_timestamp_updated_at\" cannot be tracked for the following reasons:\n  • the function does not return a \"COMPOSITE\" type\n  • the function does not return a SETOF\n  • the function does not return a SETOF table\n  • function of type \"VOLATILE\" is not supported now\n",
            "type": "function"
        }
    ],
    "path": "$.args[1].args",
    "error": "in function \"set_current_timestamp_updated_at\": the function \"set_current_timestamp_updated_at\" cannot be tracked for the following reasons:\n  • the function does not return a \"COMPOSITE\" type\n  • the function does not return a SETOF\n  • the function does not return a SETOF table\n  • function of type \"VOLATILE\" is not supported now\n",
    "code": "constraint-violation"
}```

I clicked the track checkbox when running `db-init.sql` the first time (although the instructions in the README do not say to), and that's when I got this error. Unchecking the track checkbox let me run it.

**Comment by plmercereau** [comment]
Interesting. Still it won't happen anymore in hbp v2 as we will use the new migration system from the hasura cli
