### ISSUE TITLE
Purpose of this project and 3factor apps

### ISSUE THREAD

**Issue by yourtallness** [nhost/hasura-backend-plus#245]
I learned of this project though [this great writeup](https://hasura.io/blog/best-practices-of-using-jwt-with-graphql/).

In the post they are actually using a backend repo based on HBP and not vanilla HBP, so I don't know what extra functionality they implemented on top of it.

Being a backend dev with experience in monolithic apps, I have a number of questions:

1. Is HBP + hasura essentially what you are getting when signing up to nhost.com, but this project exists in case someone wishes to self-host?
2. Is HBP meant to be extended in any way or should it always be used unmodified?
3. In a 3factor architecture, the developer is expected to code the SPA & serverless functions, while hasura & HBP are supposed to be configured only?
4. One core functionality of this project is to offer a way for SPAs to avoid implicit oauth flows (and storing JWTs in local storage etc) and instead use an auth server that can set httponly cookies for (something like) session support, right?
5. Can HBP support 2FA e.g. only for users with an admin role, or will it apply to all if enabled? I would find it interesting for the admin with access to an admin panel, but wouldn't want the burden of 2FA on simple users.
6. If we were to need a service that should be able to insert / modify data as well (besides the CRUD operations exposed by hasura), e.g. create 2-3 types of records in a transactional manner, where in this stack would be the place to do that and how? From serverless functions? Using custom mutations or direct db access?
7. What is an example of an external GraphQL schema we might want to stitch with the one hasura exposes?
8. There are many sections of the HBP documentation that are stubs and have not been expanded yet. This is a bit worrisome. Is there a rough ETA on when the documentation will be completed? (The documentation on nhost.com on the other hand is much more complete)
9. Are hasura and HBP on a managed nhost installation kept up to date regularly?
10. Is file post-processing possible for e.g. generating image versions (thumbnail, medium, large) etc like one can do with Cloudinary?

Thanks in advance and please let me know if these questions should be asked elsewhere, e.g. in a Google Group.

**Comment by elitan** [comment]
Great questions!

1. Yes ([nhost.io](https://nhost.io), not .com) ;)
2. Unmodified
3. Yes
4. Yes
5. Right now you can only enable (not enforce) 2FA. Maybe we could create a new issue about this to discuss.
6. You can already create a transactional insert with multiple records with Hasura. Check here: https://hasura.io/docs/1.0/graphql/manual/mutations/multiple-mutations.html#execution. But for some data access you need to write custom code and then you would use actions, remote schemas or event triggers. We use Hasura internally at Nhost and we have maybe 10% of API calls on such methods. The other 90% Hasura handles.
7. It's up to your imagination. Check out https://www.onegraph.com/
8. Rough ETA 1-3 months to complete.
9. On Nhost you can update Hasura version your self, HBP versions updates regularly.
10. No, but that's on our todo to research and implement if possible.

@plmercereau might add more info and context here soon.

If you want to talk more directly you can join our Discord server here: https://discord.gg/mBK2QSq. Otherwise issues like this are 100% OK!

**Comment by yourtallness** [comment]
@elitan Thank you for the answers!

I'll read up on onegraph & schema stitching in general.

Not even sure I am going to need another graphql server at all, but having to set up one from scratch sounds like a real pain compared to the magic of hasura.

There's too much choice on how to set up a graphql server oneself (prisma + nexus, apollo server, express-graphql, type-graphql, postgraphile & more) so it's kind of hard for a graphql beginner to make an educated guess on which path to take.

I have joined discord as well, thanks for the invite.

I'll leave the current ticket open for a while in case your co-maintainer would like to contribute.

**Comment by elitan** [comment]
Awesome, and just shoot me/us more questions or let me know if you want me to elaborate on some of the answers.
