### ISSUE TITLE
upload very large files

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#298]
I'm wondering if it is currently possible to upload very large files to HBP.
If not we could consider using something like
https://www.npmjs.com/package/express-fileupload#using-busboy-options

**Comment by aaronhayes** [comment]
Another option would be to use a presigned upload url https://docs.minio.io/docs/upload-files-from-browser-using-pre-signed-urls

1. Make request to HBP server `POST /storage/presign/o/<key>`. This returns the pre-signed URL 
2. User uploads to url

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
