### ISSUE TITLE
Update docs with working docker-compose.yaml file that works out of the box.

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#325]
- [ ] Example docker-compose.yaml file that works out of the box

**Comment by TimNZ** [comment]
+1 
It's definitely implied that the docker-compose.yaml on the get started is supposed to work out of the box, but is clearly out of date.
I'm still trying to figure out what to do make it work.
There's an env-var-checks.ts that fails because of missing env var, which includes DATABASE_URL, and that var isn't even referenced in the docs.

Also tried:
https://github.com/nhost/hasura-backend-plus/blob/master/docker-compose.yaml

**Comment by elitan** [comment]
Totally agree. This has not been prioritized from our side. But we'll clean up this repo in the coming days and provide better docs and examples. I'm actively working on it right now.
