### ISSUE TITLE
support Hasura migrations config v2?

### ISSUE THREAD

**Issue by zwl1619** [nhost/hasura-backend-plus#331]
Support Hasura migrations config [v2](https://hasura.io/docs/1.0/graphql/core/migrations/upgrade-v2.html)?

**Comment by plmercereau** [comment]
Hello,
HBP uses config v1 because v2 actually replaces the entire metadata. In using config v1, it is possible to keep the pre-existing metadata when installing HBP. You can see this [discord thread](https://discordapp.com/channels/407792526867693568/428469959530643466/709062301331882075) for further information.

We could have used config v2, but it would have worked only on DB where no metadata has been installed yet.

In the meantime, if you want to use config v2 for your projects, you can:
1. have anything pre-installed DB with v2 migrations and metadata
2. install HBP in running the v1 migrations (or in using `AUTO_MIGRATE`)
3. re-fetch metadata in running `hasura metadata export`
4. continue your config v2 project

I hope it answers your question.
