### ISSUE TITLE
Phone SMS Registration support

### ISSUE THREAD

**Issue by smblee** [nhost/hasura-backend-plus#338]
Hello,

I am curious if phone # registration is a possibility (using SMS code verificaiton)?

Firebase already has this functionality (1000 requests for free a month... but they are google). I am thinking we can utilize Twillio for this feature, or some other services that I may not know.

**Comment by janakact** [comment]
+1  This is a very much needed for me. 
We need to let our users to login without an email address or a password. We just ask for the phone number and send the OTP. 

If we can have an admin API endpoint to generate jwt-token for a give user, we can achieve this.

**Comment by elitan** [comment]
Yea, this would be great.

Should we support only Twillio or is there a more general approach (like SMTP for email)?

**Comment by plmercereau** [comment]
The biggest problem that I see is that until now, HBP uses emails to identify users. Does you imply registration would occur with a phone number rather than an email @smblee ?

Set this point aside, I think there is no standard for API gateways - each vendor tend to implement their own specs. 
Although Twillio is probably the most popular, I would avoid to close the possibility of adding other vendors at a later stage. We could then develop some kind of generic code in the same way that we did for several providers and include the current SMTP , e.g. in defining a `ACTIVATION_METHOD` env var that would point to an enum value that could be `email`, `twillio` and so on. If doing so, we could also possibly drop the `AUTO_ACTIVATE_NEW_USERS` and replace it by `ACTIVATION_METHOD=none`.

**Comment by janakact** [comment]
Yeah. HBP needs an email, so first I was thinking of generating a fake email using the phone number (Example: phone_no@example.com). 
Or we can do like facebook provider does.. It create users without email addresses. it uses `auth_provider_unique_id` field in the account providers table as the unique identifier..  

For my use-case I am using a local SMS gateway(not Twilio). Anyway if I can setup a web-hook for that, it will be enough.

**Comment by janakact** [comment]
@smblee  I did some modifications in order to support a passwordless strategy. https://github.com/janakact/hasura-backend-plus/pull/2/files
Anyway it is not a clean implementation but I am going to use it until we figure-out this clearly.  ;) 
My plan is to set the webhook to a seperate nodejs application (which we already have for other custom functionalities) and handle the SMS gateway integration from there.

**Comment by elitan** [comment]
I'm thinking email and sms could be two independent register/login solutions.

Just like you can add a Github login to your email/password account.

The way I see it we would need:

- enable/disable SMS register/login globally
- add sms/phone column somewhere together with a flag `is_active`. Ex: `account.phone_number` and `account.phone_number_is_activate`. The problem here is that we currently have a single `account.active` that's globally on the account.

When it comes to use different vendors I think we should make a way to add different vendors (custom code in HBP) and then use env vars to configure which one to use. 

The big problem I see is how to set up the database schema for this.

Possible we should use an external schema. `auth.account_sms` or something.

**Comment by mnlbox** [comment]
@smblee This is my old PR for adding this feature but unfortunatly @elitan didn't find time to review this at that time: https://github.com/nhost/hasura-backend-plus/pull/29

So you just need to call your favorite SMS endpoint (REST or any other way you like) or any other third API (email, authunticator app, ..) here in this line:
https://github.com/nhost/hasura-backend-plus/pull/29/files#diff-cda8c3573017739b9bc19105ceceac90a92c83d2eb130fb2987f54872a91e2e9R27

Now I'm using this implemetation and my fork in 2 systems in production for near 1 year and it worked without any issue until now.


But It's better to implement this again in this new HB+ because my fork is very old and based on the JS version of HB+. Now HB+ has a lot of more feature compare to that time. (Thanks @elitan :wink:  )

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
