### ISSUE TITLE
Exposing Rest API as Hasura actions

### ISSUE THREAD

**Issue by ziahamza** [nhost/hasura-backend-plus#345]
Right now there is a REST API implemented, but would be really cool to instead expose that as a Hasura GraphQL actions, especially with anonymous access (so do not require pre-authentication). This would allow a single API to connect to database, and to handle authentication and authorization

The storage and upload mechanism will still have to be a REST API, but rest works really well as an action. Hasura allows forwarding cookies / headers so authentication can easily be done through Actions without requiring a REST API. 

Works really well with #344  to make sure the frontend is correctly using the API (even as the API changes over time)

To achieve backward compatibility, a decent approach may also be to expose API both through REST and Hasura Actions (and internally use the same set of code)

**Comment by ziahamza** [comment]
potentially duplicate of #256 . Actions are slightly better as they dont require custom GraphQL server to be built (and integrate with existing schema much better then remote schemas at this stage in time)

**Comment by elitan** [comment]
I don't see the benefit of this.

This means more complexity and more to maintain.

Also [`nhost-js-sdk`](https://github.com/nhost/nhost-js-sdk) makes it easy to use both auth and storage.

**Comment by plmercereau** [comment]
I would tend to agree with you @elitan.
However, a benefit would be to be able to expose one single endpoint (Hasura) instead of two (Hasura+HBP). But as long as storage requires to be exposed (which will be likely be always the case e.g. GET requests used in download link), I think it is wiser to keep it as simple as possible.

However @ziahamza I think this could be implemented quite easily aside of HBP, it could be a nice recipe to put in the documentation, don't you think?

**Comment by elitan** [comment]
I'm closing this for now since it's not on our radar at the moment and to clean up the issues in the repo.
