### ISSUE TITLE
Add `me` as role for new users.

### ISSUE THREAD

**Issue by elitan** [nhost/hasura-backend-plus#364]
This way, we can use `x-hasura-role=me` when interacting (Read/Update) personal user information.

**Comment by aaronhayes** [comment]
Just need to update the defaults, as the env variable `DEFAULT_ALLOWED_ROLES` will cover this use case.

**Comment by elitan** [comment]
> Just need to update the defaults, as the env variable `DEFAULT_ALLOWED_ROLES` will cover this use case.

Yes.

**Comment by plmercereau** [comment]
I don't get it: I would have set hasura permissions to the user table so an user can only read/write it's own details.

**Comment by elitan** [comment]
Sometimes you want all users to be able to read ex `id` and `display_name` but not ex `birthday`.

However, the users should be able to read its own `birthday`.

**Comment by aaronhayes** [comment]
This can be closed now @elitan

**Comment by plmercereau** [comment]
@elitan valid point. I personally think this way of handling roles is a workaround due to Hasura limitations. Hopefully [multiple roles](https://github.com/hasura/graphql-engine/issues/877) or [multiple row + column permissions](https://github.com/hasura/graphql-engine/issues/3442) will be implemented soon - although I lost hope after waiting for almost two years... Still, both are on [Hasura's roadmap](https://github.com/hasura/graphql-engine/projects/1).

**Comment by koo5** [comment]
very confusing
