### ISSUE TITLE
make token fields prefix configurable

### ISSUE THREAD

**Issue by cyclops24** [nhost/hasura-backend-plus#376]
Hi @elitan ,

Now Hasura supports [claims_map](https://hasura.io/docs/1.0/graphql/core/auth/authentication/jwt.html#claims-map) and it means the users can use a custom prefix for the token fields rather than `x-hasura-` prefix. I checked the code and it seems we can simply implement this feature with reading prefix from an environment variable rather than a hard code version here:
https://github.com/nhost/hasura-backend-plus/blob/21681267dfdbcb3bf3abcf181238f6640705d65c/src/shared/jwt.ts#L66

Are you agree and like this idea?
If yes, I can also prepare a PR for this.

**Comment by elitan** [comment]
Yes it's possible but why?

The way I see it, it will only increase the configuration for Hasura.

**Comment by cyclops24** [comment]
In some project for security reason I prefer to hide my exact backend technology from end user, by setting this environment variable I can remove this prefix or set it to some dummy value.
We can keep `x-hasura-` as a default value so if a user don't need this, they can ignore this totally.

**Comment by elitan** [comment]
Sounds OK.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
