### ISSUE TITLE
Allow to open Auth in popup

### ISSUE THREAD

**Issue by kapik** [nhost/hasura-backend-plus#425]
Hey 👋 ,

I'm trying to open the auth provider in popup.
It works well when the caller is in a classic window/tab.
However, when the caller is in an iframe, it is not possible to open this popup: 

> ERROR DOMException: Blocked a frame with origin "https://...//auth/providers/google" from accessing a cross-origin frame.

I think that cros-origin via iframe is not allowed because of this header: `X-Frame-Options: SAMEORIGIN`
According to the server configuration, it is `helmet` that would add this header.

I couldn't find an option to configure this. 
What do you think? Do you have a solution to allow this behavior?

Thank you for your help

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
