### ISSUE TITLE
Casing of file metadata's "key" field inconsistent across storage APIs

### ISSUE THREAD

**Issue by shyndman** [nhost/hasura-backend-plus#436]
The response from a POST to `/storage/o/file` is key (lowercase):
https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/storage/upload.ts#L95

The `/storage/m/directory/` is Key (capitalized):
https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/storage/list.ts#L47

The `/storage/m/file` is key (lowercase):
https://github.com/nhost/hasura-backend-plus/blob/master/src/routes/storage/list.ts#L47

These all represent the same data, and consistency would make deserialization easier on the client.

My personal opinion is that going with `key` (lowercase) is the better option. The other PascalCase fields in the response appear to represent HTTP response headers, of which key is not one.

**Comment by RubenVanEldik** [comment]
Thank you for pointing this out and creating such a clear issue with a proposed solution. I just looked into it seems that only the response for the directory metadata is not conform the other responses. (all other responses are lower case)

I created a PR (https://github.com/nhost/hasura-backend-plus/pull/451), since its just a single character that needed to be replaced. :p

**Comment by shyndman** [comment]
You're welcome. Thanks for the update.

**Comment by elitan** [comment]
Merged and released 🎉
