### ISSUE TITLE
Use a logger library

### ISSUE THREAD

**Issue by komninoschat** [nhost/hasura-backend-plus#468]
We currently use the native Node.js `console` family of functions to perform our logging. I propose we switch to a more powerful library, like [winston](https://github.com/winstonjs/winston) which I have used before with much success.

Doing this will give us a lot more flexibility in terms of logging, e.g. saving logs to files, filtering out log data in terms of level or scope, and avoiding weird hacks like the one below from [test-utils.ts](/nhost/hasura-backend-plus/blob/master/src/test/test-utils.ts#L7):
```typescript
// eslint-disable-next-line @typescript-eslint/no-empty-function
console.error = function (): void {} // Disable the errors that will be raised by the tests
```

**Comment by komninoschat** [comment]
Take #409 into account.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
