### ISSUE TITLE
Get and Upload files via presigned URLs

### ISSUE THREAD

**Issue by aaronhayes** [nhost/hasura-backend-plus#472]
Using pre-signed URLs, a client can upload files directly to our S3 bucket without exposing the S3 credentials to the user. This can be really useful for a number of applications. 
1. Uploading large files directly to S3 rather than via HBP
2. Sharing files with external people securely (presigned urls expire) 
3. Accepting files securely from external people

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.

**Comment by ash0080** [comment]
> We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 
> 
> We’ll have your issue in mind when developing the new services. So thanks for filing this issue
> 
>  This means I’ll close this issue for now.

Actually the current architecture is very stupid, pulling files from HBP as buffer leads to wasted internal traffic but nothing, I hope you will solve this problem in the new version.
