### ISSUE TITLE
Convert table roles to enum

### ISSUE THREAD

**Issue by alveshelio** [nhost/hasura-backend-plus#474]
I believe that having the table roles as an enum would be a good way to prevent mistakes when adding a role to a user. 
Having a table as enum helps prevent typos that could happen when assigning a role to a user.

If I would have a table `roles` that is not an enum then the only constrain right now would be for the input to be a String, however if we'd have the table as an enum, then when we introspect the GraphQL endpoint it will generate a type role and this  input would be of this type that would only allow us to send these values in the table.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
