### ISSUE TITLE
JWT_CUSTOM_FIELDS not working

### ISSUE THREAD

**Issue by easeccy** [nhost/hasura-backend-plus#494]
I'm running the HBP from source. In .env file, I've set JWT_CUSTOM_FIELDS to some custom column in my `users` table. Custom field does not show up in the response. No errors are logged.

**Comment by elitan** [comment]
Could you provide me with the following to try to debug this:

- The value of your `JWT_CUSTOM_FIELDS`
- The columns in your `users` table
- How you register users. Do you use `nhost-js-sdk`? What version? How do you do the `auth.register()` call?

**Comment by easeccy** [comment]
Current configuration goes like this.

JWT_CUSTOM_FIELDS=address

I'm registering users with REST calls.

**Comment by elitan** [comment]
Do you have a column named `address` in the `users` table?

Can you provide the full REST request payload?

**Comment by easeccy** [comment]
Oh, I have a question at this point. I thought it was used for retrieving the data for the user that's been authenticated, not used at the registering step. Is it right?

Here is the repsonse from '/auth/login' endpoint:

```
{
  "jwt_token": "...",
  "jwt_expires_in": ...,
  "user": {
    "id": "...",
    "display_name": "...",
    "email": "..."
  }
}
```

**Comment by easeccy** [comment]
`address` column exists in `users` table. In fact, I'm fetching it with GraphQL request seperately, until I discovered that there is an easy way to retrieve it in the response from login endpoint.

**Comment by elitan** [comment]
Oh, sorry. I was also a bit confused.

If you set `JWT_CUSTOM_FIELDS=address` the `address` will be part of the JWT token as a claim that can be used for permission in Hausra (`x-hasura-address`).

Try copy the JWT token you get [here](https://jwt.io/) and you should see the address.

We don't include it directly in the `user` object that is returned from `/login`. But maybe we should? cc @nunopato

Generally I would recommend to fetch data from GraphQL.

**Comment by easeccy** [comment]
Oh, okay.

I also think that getting user details from GraphQL is nicer, therefore no need to implement it. But setting initial user data is needed. In an ordinary signup form, there are fields like phone, gender etc. AFAIK it is not possible to create user with additional info, and therefore after the signup, I'm redirecting users to the second step to complete registration. Sometimes multi-step register flow is overkill (eg. just to get phone number). One poor alternative is to signup the user and then make a "secret" mutation to the database to fill the info, which could lead to a dirty state in case if network connection is lost after the signup.

**Comment by ArieJones** [comment]
You shouldn't have to fetch it seperately.... there is a method on auth for getClaim that can be used to grab the value.

I am currently using a couple of different custom fields that I set during registration and just use some small helper utilities to get the value using the auth method. The only difference in my case is that I am having to call the api endpoint so that the user is not auto-magically logged in.. because it is done on an admin panel. 

You just need to ensure that you have permission set to insert it during registration(Registration Custom Fields) 
** REGISTRATION AND JWT CUSTOM FIELDS MUST MATCH **  
example 
`REGISTRATION_CUSTOM_FIELDS=avatar_url,display_name,clientId
JWT_CUSTOM_FIELDS=avatar_url,clientId,display_name`

... and then you're off and running. 

Hope that helps!
