### ISSUE TITLE
Support SMS MFA

### ISSUE THREAD

**Issue by joshmedeski** [nhost/hasura-backend-plus#508]
# User Story
As a user, I want to decide what two-factor authentication method I want to use so that I can increase the security of my account in the most convenient way possible.

# Notes
- Google offers multiple MFA methods at the same time (ex: Authentication app AND SMS are supported). This would take some significant architectural changes.
- SMS could be done through a third party API and just the endpoint could be configured

I have potential clients that would want this feature, so I can personally commit to working on this if we can decide on the best approach to solving it.

**Comment by elitan** [comment]
Discussion on SMS support is also discussed here: https://github.com/nhost/hasura-backend-plus/issues/338

**Comment by joshmedeski** [comment]
@elitan I read through that issue. This is related to using SMS for two-factor authentication, not using a phone number for registration (different purposes).

**Comment by elitan** [comment]
Yep, different purposes. But the underlying SMS implementation should be shared across these issues. So I just wanted to link them.

**Comment by cweagans** [comment]
It seems strange to add support for a 2FA mechanism with known vulnerabilities with a track record of exploitation. I would suggest not moving forward with this (neither for HBP nor for @joshmedeski 's client that wants it) given how simple SIM swap attacks are these days. Most US mobile providers will do it with just a SSN, which are all effectively public after the Equifax breach. It would be way safer to text a link to a page that lets you use a previously configured FaceID, U2F token, or similar as a second factor -- that would at least guarantee that the SMS message is getting to the right device (since FaceID and TouchID signatures are locked to one specific device; + the U2F key built into some Android phones is also locked to one specific device)

**Comment by joshmedeski** [comment]
This is a fair point @cweagans. I have a client that wants to use this feature, even though these vulnerabilities are a reasonable concern. Perhaps we could put a warning in the documentation warning people of the potential issue this feature could cause.

But SMS 2FA is better than no 2FA in my opinion :)

**Comment by cweagans** [comment]
Non-tech-savvy users put their passwords on sticky notes and [tweet a picture of it](https://www.theregister.com/2021/06/07/brooks_gmail_password/), but that doesn't make it a good idea.

SMS 2FA is _barely_ better than no 2FA these days. Like this:

![image](https://user-images.githubusercontent.com/101590/121749505-028d0b80-cac8-11eb-9baf-7128f036547b.png)

If this goes in, I strongly support adding some documentation explicitly stating that this is security theater and really doesn't add any protection.

**Comment by joshmedeski** [comment]
Thanks for the feedback, let's see what @elitan says since he's the product owner.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repositories are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
