### ISSUE TITLE
Question: Verify existing email during registration

### ISSUE THREAD

**Issue by mrcasablr** [nhost/hasura-backend-plus#596]
Hello! 

Was wondering if there is an API to check if an email is already registered. I would like to async verify if the email exists while the user is filling the registration form. 

If this belongs to the sdk repo please let me know, I will create a issue there instead.

**Comment by elitan** [comment]
There is not. And that would basically open up the possibility for anyone to check what emails are registered on your service which is information you might not really want to give away.

I would suggest to not display such information.

**Comment by mrcasablr** [comment]
It's no different than someone trying to create an account with someone's email with password to check if account exists?  If account is registered you will have to throw an error that account exists anyway.

**Comment by elitan** [comment]
True.

To answer your first question: There is no such endpoint and we don't plan to add it.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently these new repos are private but will be open sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
