### ISSUE TITLE
Whitelist Extension

### ISSUE THREAD

**Issue by fullakingi** [nhost/hasura-backend-plus#599]
Late to the party on this (flowed thru from feature requests 555, 547).  Thanks so much for the whitelist. Very, very grateful for your work and discussion. 

Just want to confirm functionality:

If WHITELIST is used, an invite email template is sent to the admin with the email address (or other form fields) of the user requesting access. 

When the admin approves the user they will be given access. If the admin does not approve the user they will not be added to the whitelist.  
 
 Q. So what list are the non-confirmed users be on?  BLACKLIST? 

 Q. Is it possible to also poll  the userfor more information from the user at the initial request to be on the whitelist? For example a form
 
 RATIONALE / BUSINESS LOGIC
 I notice that many services, particularly start-ups require free data from user in return for freemium services - email, name, credit-card or topic specific data.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently these new repos are private but will be open sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.

**Comment by nikolowry** [comment]
@elitan advice for those of us that were using a pre-release Docker image so we could use these features early? And are these new repos going to be "add-ons/extensions" to HBP? 

My app's dependent on this type of invite/allow functionality -- I need to decide if I need to fork HBP and build custom images with patches, continue using the pre-release images until the new open source repos you mentioned or explore new solutions. 

Thanks in advance

**Comment by elitan** [comment]
@nikolowry Yea I totally understand your situation.

The next version of HBP, which will include whitelisting/invitation, is not yet public but will be open source as soon as it's stable in the coming months. It will not be an "extension" but a full replacement.

If you need the functionality now your best option is maybe to fork and implement it your self if you can't want a few months.

**Comment by fullakingi** [comment]
Hi guys, I just looked in the discord but is too many messages to find what I need. I am still very keen on this so our team start to make this feature, let us know if you need it or you have developed a repo. @nikolowry @elitan

**Comment by nikolowry** [comment]
@fullakingi I've been pinned to the HBP Docker image of `nhost/hasura-backend-plus:pr-556-merge` since my last comment.

At that time, this was the first Hasura project I've ever worked in and my SQL experience was somewhat limited. After 4 months, I've gotten better at writing SQL and understanding Hasura.

My plan in the next couple of weeks was to get back on `nhost/hasura-backend-plus:lastest` by enforcing the `auth.whitelist` with a SQL CHECK constraint. I'll the solution when I have it, but there's other deadlines and vacation that's blocking me from tackling it now.

**Comment by fullakingi** [comment]
Thank you for the message @nikolowry 🤙 . I am working with @TheOsch on it, he is in Russia and I am in NZ, so we have 3 hour window which is communication time so we might be week or so just to get aligned. BTW - I am learning myself and have no expectations, I am a self-taught graphic designer, self-taught front end and just barely get by on GraphQL. TheOsch will probably have more ideas than me.
