### ISSUE TITLE
HBP with DBs other than postgresql e.g. MSSQL

### ISSUE THREAD

**Issue by plmercereau** [nhost/hasura-backend-plus#607]
Playing the devil's advocate here.
HBP now runs migrations in connecting directly to PostgreSQL instead of using the built-in Hasura migration system.
It implies HBP would not work with other DBs than Postgres, or that we will need to re-write migrations for MSSQL and each DB system Hasura would set in the future.

**Comment by elitan** [comment]
We’ve decided to only fix bugs and refactors on Hasura Backend Plus from now on because we’re working on a new auth + storage service for Hasura. Currently, these new repos are private but will be open-sourced soon. 

We’ll have your issue in mind when developing the new services. So thanks for filing this issue

 This means I’ll close this issue for now.
