### ISSUE TITLE
Support for multi-tenancy

### ISSUE THREAD

**Issue by SharadKumar** [nhost/hasura-backend-plus#94]
How about adding support for multi-tenancy?

@elitan You've done fantastic breakdown and guidance in [your post on multi-tenancy](https://nhost.io/blog/building-a-multi-tenant-application-with-nhost-and-hasura). I am proposing if this could be first-class support, or a guidance specific to HB+.

For example, I see users email are set to be UNIQUE but in a multi-tenant scenario, same person (email) might register with two different domains (domain1.com and domain2.com, using the same common multi-tenant backend, common to SaaS use cases) using the same auth provider.

Maybe it is just a guidance (`/examples` folder?), or a first-class feature of HB+?

**Comment by elitan** [comment]
Thanks. Sorry for the late answer.

I see your point, but could you clarify it a bit?

In what scenario would the same person (email) register on your multi-tenant system? Could you give me an real world example?

**Comment by SharadKumar** [comment]
Lets say Hasura is used to create a SaaS product (lets say, Shopify model). Product wants to allow clients (business entity or store tenant) and their customers (individual users per particular tenant) to be registered to use the product. 

So when the product is live, let's say Joe Blogs (joe.blogs@gmail.com) registers as a customer of Tenant1, while shopping.  Laters he also does shopping with Tenant2 store (with same email).

Similarly, there could be another SaaS case whereby App allows teams be defined (very common use case, lets say similar to Digital Ocean admin). Joe Blogs is part of two separate teams and each team is a separate tenant (domain perhaps, depending on the SaaS design). 

It quite aligns with your thinking in the Blog, it is just that I don't see it supported or available in this repo.

**Comment by yourtallness** [comment]
@elitan While I don't know the OP's exact intentions, having worked on a multi-tenant app, the following come to mind:

- Per tenant data may be kept in separate PG schemas
- The might be common data across schemas for entities that exist only once (e.g. 
- The tenant for each http / api request is determined by a criterion like subdomain or even fully qualified domains

Perhaps the OP is talking about baking in support to HBP for this kind of use.

I could imagine a use case where a single user would like to be able to shop from different tenants, but have a single account.

This would require the cookie to be set without subdomain, so that it can work on all subdomains.

Tenants might want some kind of data separation instead of having it all in the same schema.
This makes imports / exports etc easier as well.
Associations between shared and per-tenant records may be a pain though.

Ruby gems like [apartment](https://github.com/influitive/apartment) offer db / schema switching for multi-tenancy; the ORM connects to the tenant's db / schema prior to making any db calls.

**Comment by elitan** [comment]
Ok, understood.

For now we will not support to have multiple accounts for different tenants.

For now, the focus is to support a single application with user/files together with Hasura.

I'm closing this issue, but we'll keep the conversation here if anything changes in the future.
